In [2]:
from sklearn import datasets
import numpy as np 
from sklearn.metrics import confusion_matrix
import skfuzzy

# Algoritmo Fuzzy C-means
 
O algoritmo Fuzzy C-means, é uma variação
do algoritmo de K-means, onde ele
possibilita tratar incertezas, ou seja, dados
que possuem características de dois
diferentes grupos. Estes são classificados a
partir de um “grau de pertinência” de cada
grupo (Yonamine [5]). O grau de pertinência
descreve o quanto de semelhança ou
proximidade, determinado elemento tem de
cada grupo, indicando que o grupo ao qual
este determinado dado pertence é aquele que
o que possui maior grau de pertinência. 

In [3]:
iris = datasets.load_iris()

In [4]:
# iris.data.T = fazendo tranposição da matrix, o que linha vira coluna, e o que linha vira coluna
# n = numero de cluster
# m  = ao qual grupo o dado pertence, 2 é default
# error =  criteiro de parada
# maxiter = quantas vezes vai fazer a reptição
resultado = skfuzzy.cmeans(data = iris.data.T, c = 3, m = 2, error = 0.005,
                          maxiter = 1000, init = None)
resultado

(array([[6.77433912, 3.05218649, 5.6459439 , 2.05322299],
        [5.88837668, 2.76086907, 4.36313969, 1.39689658],
        [5.00396466, 3.41411633, 1.48277077, 0.25352624]]),
 array([[1.07191814e-03, 7.50159827e-03, 6.41693839e-03, 1.01123217e-02,
         1.76788895e-03, 2.06280203e-02, 6.50699883e-03, 1.41272738e-04,
         2.19114774e-02, 5.34433096e-03, 1.02044852e-02, 2.43247340e-03,
         9.18128187e-03, 2.52445639e-02, 3.76424920e-02, 5.43221736e-02,
         1.75009237e-02, 1.05882783e-03, 3.03197942e-02, 6.65568524e-03,
         9.54526595e-03, 4.79555799e-03, 1.38362270e-02, 6.11588265e-03,
         9.84405003e-03, 7.97817950e-03, 1.57471043e-03, 2.08742335e-03,
         1.99648228e-03, 6.28600972e-03, 6.47723059e-03, 7.94320157e-03,
         2.03401841e-02, 3.23577994e-02, 4.59660750e-03, 4.80657273e-03,
         1.15677897e-02, 2.92684698e-03, 1.92399748e-02, 5.33488843e-04,
         1.68828425e-03, 4.70116322e-02, 1.52140255e-02, 6.33304077e-03,
         1.66086482e-

In [5]:
previsoes_porcetagem = resultado[1]
previsoes_porcetagem

array([[1.07191814e-03, 7.50159827e-03, 6.41693839e-03, 1.01123217e-02,
        1.76788895e-03, 2.06280203e-02, 6.50699883e-03, 1.41272738e-04,
        2.19114774e-02, 5.34433096e-03, 1.02044852e-02, 2.43247340e-03,
        9.18128187e-03, 2.52445639e-02, 3.76424920e-02, 5.43221736e-02,
        1.75009237e-02, 1.05882783e-03, 3.03197942e-02, 6.65568524e-03,
        9.54526595e-03, 4.79555799e-03, 1.38362270e-02, 6.11588265e-03,
        9.84405003e-03, 7.97817950e-03, 1.57471043e-03, 2.08742335e-03,
        1.99648228e-03, 6.28600972e-03, 6.47723059e-03, 7.94320157e-03,
        2.03401841e-02, 3.23577994e-02, 4.59660750e-03, 4.80657273e-03,
        1.15677897e-02, 2.92684698e-03, 1.92399748e-02, 5.33488843e-04,
        1.68828425e-03, 4.70116322e-02, 1.52140255e-02, 6.33304077e-03,
        1.66086482e-02, 8.63569380e-03, 7.36745629e-03, 8.13011521e-03,
        7.26189005e-03, 9.19565633e-04, 5.01750112e-01, 2.07411510e-01,
        6.00706882e-01, 8.03351421e-02, 2.17874600e-01, 2.047217

In [8]:
previsoes_porcetagem[0][0]
previsoes_porcetagem[1][0]
previsoes_porcetagem[2][0]



0.9966236357853403

In [9]:
#argmax = pegar o maior valor
#axis = 0   pegar o maior valor por coluna
previsoes = previsoes_porcetagem.argmax(axis = 0)
previsoes

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1])

In [10]:
resultados = confusion_matrix(iris.target, previsoes)
resultados

array([[ 0,  0, 50],
       [ 3, 47,  0],
       [37, 13,  0]])